# Generated by Django 3.0.4 on 2020-07-31 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flick', '0002_todoitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToDoItem',
        ),
    ]
